language: bash

os:
- linux

env:
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5.0

matrix:
  include:
    - os: osx

services:
  - docker

script:
- |
  cat <<Dockerfile | docker build --build-arg bashver=${BASHVER} --tag bats/bats:bash-${BASHVER} -
  ARG bashver=latest

  FROM bats/bats:latest as bats
  FROM bash:\${bashver}

  # Install parallel and accept the citation notice (we aren't using this in a
  # context where it make sense to cite GNU Parallel).
  RUN apk add --no-cache parallel && \
      mkdir -p ~/.parallel && touch ~/.parallel/will-cite

  RUN ln -s /opt/bats/bin/bats /usr/sbin/bats
  COPY --from=bats /opt/bats /opt

  ENTRYPOINT ["bash", "/usr/sbin/bats"]
  Dockerfile
  docker run -it bash:${BASHVER} --version
  time docker run -it bats/bats:bash-${BASHVER} --tap /opt/argsh/tests
notifications:
  email:
    on_success: never